from aws_lambda_powertools import Logger, Tracer, Metrics
from aws_lambda_powertools.metrics import MetricUnit
from enum import Enum

SERVICE_NAME = "worker-process"

logger = Logger(service=SERVICE_NAME)
tracer = Tracer(service=SERVICE_NAME)
metrics = Metrics(namespace="RaffleNow", service=SERVICE_NAME)


class ErrorCodes(str, Enum):
    INVALID_EVENT_TYPE = "INVALID_EVENT_TYPE"
    MISSING_RAFFLE_ID = "MISSING_RAFFLE_ID"
    RAFFLE_NOT_FOUND = "RAFFLE_NOT_FOUND"
    INVALID_RAFFLE_STATUS = "INVALID_RAFFLE_STATUS"
    NO_PARTICIPANTS = "NO_PARTICIPANTS"

    WINNER_SELECTION_ERROR = "WINNER_SELECTION_ERROR"
    DATABASE_UPDATE_ERROR = "DATABASE_UPDATE_ERROR"
    WINNER_RECORD_ERROR = "WINNER_RECORD_ERROR"
    EMAIL_SEND_ERROR = "EMAIL_SEND_ERROR"
    SES_NOT_CONFIGURED = "SES_NOT_CONFIGURED"

    PROCESSING_ERROR = "PROCESSING_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class Actions(str, Enum):
    BATCH_STARTED = "BATCH_STARTED"
    RECORD_PROCESSING = "RECORD_PROCESSING"
    RECORD_SKIPPED = "RECORD_SKIPPED"
    BATCH_COMPLETED = "BATCH_COMPLETED"

    RAFFLE_VALIDATED = "RAFFLE_VALIDATED"
    PARTICIPANTS_QUERIED = "PARTICIPANTS_QUERIED"
    WINNER_SELECTED = "WINNER_SELECTED"
    RAFFLE_COMPLETED = "RAFFLE_COMPLETED"
    RAFFLE_FAILED = "RAFFLE_FAILED"

    WINNER_RECORD_CREATED = "WINNER_RECORD_CREATED"
    EMAIL_SENT = "EMAIL_SENT"
    EMAIL_FAILED = "EMAIL_FAILED"
    EMAIL_SKIPPED = "EMAIL_SKIPPED"
