sonar.projectKey=rafflenow-v2
sonar.projectName=RaffleNow V2
sonar.projectVersion=1.0.0
sonar.organization=jeancdev

sonar.sources=app/lambdas
sonar.tests=app/lambdas
sonar.test.inclusions=**/__tests__/**/*.js
sonar.exclusions=**/node_modules/**,**/coverage/**,**/venv/**,**/layer/**
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=**/__tests__/**,**/*.test.js
